# mihomo (Clash Meta) 懒人配置
# 版本 V1.8-240904
# https://gist.github.com/liuran001/5ca84f7def53c70b554d3f765ff86a33
# https://obdo.cc/meta
# 修改自官方示例规则 https://wiki.metacubex.one/example/#meta
# 尽量添加了较为详尽的注释，不理解的地方建议对照 虚空终端 (Clash Meta) Docs 进行理解
# 虚空终端 (Clash Meta) Docs 地址: https://wiki.metacubex.one


# 分组
pr:
  &pr {
    type: select,
    proxies:
      [
        节点选择,
        香港,
        台湾,
        日本,
        新加坡,
        美国,
        倍率,
        Mytvsuper,
        MytvsuperUS,
        MytvsuperHK,
        其它地区,
        全部节点,
        自动选择,
        DIRECT,
      ],
  }
# 延迟检测 URL
p: &p
  type: http
  # 自动更新订阅时间，单位为秒
  interval: 86400
  health-check:
    enable: true
    #url: https://cp.cloudflare.com
    url: https://www.gstatic.com/generate_204
    # 节点连通性检测时间，单位为秒
    interval: 43200
    # 节点超时延迟，单位为毫秒
    timeout: 1000
    # 节点自动切换差值，单位为毫秒
    tolerance: 100

LoadBalance: &LoadBalance {type: load-balance, interval: 6, lazy: true, url: 'https://www.google.com/generate_204', disable-udp: false, strategy: consistent-hashing, timeout: 2000, max-failed-times: 3, expected-status: 204, hidden: true}
# 基础配置
# --------------------------------------------------
# 如果你是小白，那么你只需要修改分割线以内的内容
# 其他部分保持不动即可
# 如果你需要使用大于两个机场，在下方 `use` 处添加 `订阅三` （名字可以自己取），然后在 `proxy-providers` 照例添加订阅链接即可
# 反之，如果你只需要使用一个，那么将 `订阅二` 前添加 `#` 进行注释即可

# 订阅名，记得修改成自己的
# 添删订阅在这里和下方订阅链接依葫芦画瓢就行
use_p: &use_p
  # 如果不希望自动切换请将下面两行注释对调
  type: select
  #type: url-test
  use:
    - ACA
    - Ash
    - PQ机场
    - JayCloud
    - YF机场
    - NiceDuck
    # - 本地配置

# 订阅链接
# 对于订阅来说，path 为选填项，但建议启用
# 本地配置可以只填 path
proxy-providers:
  ACA:
    <<: *p
    # path: ./proxy_provider/ACA.yaml
    url: "https://dadada.acaisbest.com/api/v1/client/subscribe?token=4d4e8c97ccd9f8defb788e8b838eb5e9"
    exclude-filter: "套|距|剩|官"

  Ash:
    <<: *p
    # path: ./proxy_provider/Ash.yaml
    url: "https://junnanliangnv.egfu.cn/api/v1/client/subscribe?token=666370e1eeb462deffe0a8b8a8249183"
    exclude-filter: "套|距|剩|官|去除"

  PQ机场:
    <<: *p
    # path: ./proxy_provider/PQ机场.yaml
    url: "https://xn--cp3a08l.com/api/v1/client/subscribe?token=a396deeda55a15f90e5677e9d0418b27"
    override:
      proxy-name:
      - pattern: "0.01倍"
        target: "0.01x"
    exclude-filter: "套|距|剩|官|2倍|5倍"

  JayCloud:
    <<: *p
    # path: ./proxy_provider/JayCloud.yaml
    url: "https://study.jaycloud11111.top/study?token=b2590afb3a5e508734b1d45bd777dcdf"
    override:
      proxy-name:
      - pattern: "油管无广告"
        target: ""
    exclude-filter: "套|距|剩|官"

  YF机场:
    <<: *p
    # path: ./proxy_provider/YF机场.yaml
    url: "https://www.yfjc.xyz/api/v1/client/subscribe?token=1b1502df00abe390e4acf2b1fe6e0f07"
    exclude-filter: "套|距|剩|官"
  mytvsuper:
    <<: *p
    # path: ./proxy_provider/mytvsuper.yaml
    url: "https://sub.443888.xyz/vless"
    exclude-filter: "套|距|剩|官"
  NiceDuck:
    <<: *p
    # path: ./proxy_provider/NiceDuck.yaml
    url: "https://sub1.niceduck.cloud/api/v1/client/hy?token=bb836dc16e335654378a8eacbbc4a2e3"
    exclude-filter: "套|距|剩|官"
  # 本地配置:
    # <<: *p
    # path: ./proxy_provider/本地配置.yaml

# 小白请不要继续随意修改以下设置
# 若需修改请参阅文档 https://wiki.metacubex.one
# --------------------------------------------------

# 规则订阅
rule-providers:
  # anti-AD 广告拦截规则
  # https://github.com/privacy-protection-tools/anti-AD
  # 如果误杀率高请自行更换
  anti-AD:
    type: http
    behavior: domain
    format: yaml
    # path可为空(仅限clash.meta 1.15.0以上版本)
    path: ./rule_provider/anti-AD.yaml
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-clash.yaml?"
    interval: 86400
  # anti-AD 白名单规则
  anti-AD-white:
    type: http
    behavior: domain
    format: yaml
    # path可为空(仅限clash.meta 1.15.0以上版本)
    path: ./rule_provider/anti-AD-white.yaml
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/privacy-protection-tools/dead-horse/master/anti-ad-white-for-clash.yaml?"
    interval: 86400
  #BlackMatrix7直连
  BlackMatrix7_Direct:
    type: http
    behavior: domain
    format: yaml
    path: ./rule_provider/BlackMatrix7_Direct.yaml
    url: "https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Direct/Direct.yaml"
    interval: 86400
  #秋风广告规则
  AWAvenue:
    type: http
    behavior: domain
    format: yaml
    path: ./rule_provider/AWAvenue.yaml
    url: "https://fastly.jsdelivr.net/gh/TG-Twilight/AWAvenue-Ads-Rule@main/Filters/AWAvenue-Ads-Rule-Clash-classical.yaml"
    interval: 86400
  #MetaCubeX广告规则
  MetaCubeX-AD:
    type: http
    behavior: domain
    format: mrs
    path: ./rule_provider/MetaCubeX.mrs
    url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-ads-all.mrs"
    interval: 86400
  #BlackMatrix7广告规则
  Blackmatrix7:
    type: http
    behavior: domain
    format: yaml
    path: ./rule_provider/BlackMatrix7.yaml
    url: "https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Advertising/Advertising_Classical.yaml"
    interval: 86400
  #Dustin广告规则
  DustinWin:
    type: http
    behavior: domain
    format: mrs
    path: ./rule_provider/DustinWin.mrs
    url: "https://fastly.jsdelivr.net/gh/DustinWin/ruleset_geodata@clash-ruleset/ads.mrs"
    interval: 86400
  # ACA Emby
  EmbyGYF:
    type: http
    behavior: classical
    format: text
    path: ./rule_provider/gyemb.list
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/lzanetti/fqru/refs/heads/main/gyemb.list"
    interval: 86400
  # NiceDuck Emby
  Embynd:
    type: http
    behavior: classical
    format: text
    path: ./rule_provider/niceduck.list
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/lzanetti/fqru/refs/heads/main/niceduck.list"
    interval: 86400
  #Emby qtf
  EmbyQTF:
    type: http
    behavior: classical
    format: text
    path: ./rule_provider/qtemb.list
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/lzanetti/fqru/refs/heads/main/qtemb.list"
    interval: 86400
  #TVB
  TVBTV:
    type: http
    behavior: classical
    format: text
    path: ./rule_provider/TVB.list
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/lzanetti/fqru/refs/heads/main/TVB.list"
    interval: 86400
  #倍率
  BeilvMedia:
    type: http
    behavior: classical
    format: text
    path: ./rule_provider/beilv.list
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/lzanetti/fqru/refs/heads/main/beilv.list"
    interval: 86400
  #JP
  JPPN:
    type: http
    behavior: classical
    format: text
    path: ./rule_provider/jpwz.list
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/lzanetti/fqru/refs/heads/main/jpwz.list"
    interval: 86400
  #直连
  Zhilian:
    type: http
    behavior: classical
    format: text
    path: ./rule_provider/zhilian.list
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/lzanetti/fqru/refs/heads/main/zhilian.list"
    interval: 86400
  #Streaming Global
  Streaming:
    type: http
    behavior: domain
    path: ./rule_provider/globalmedia.yaml
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Domain.yaml"
    interval: 86400
  #Tiktok
  TiktokG:
    type: http
    behavior: domain
    format: mrs
    path: ./rule_provider/tiktok.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/tiktok.mrs"
    #url: "https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@releases/download/clash-ruleset/tiktok.mrs"
    interval: 86400
  #Game_cn
  games-cn:
    type: http
    behavior: domain
    format: mrs
    path: ./rule_provider/games-cn.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/games-cn.mrs"
    #url: "https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@releases/download/clash-ruleset/games-cn.mrs"
    interval: 86400

mode: rule
# ipv6 支持
ipv6: true
log-level: info
# 允许局域网连接
allow-lan: true
# socks5/http 端口
mixed-port: 7890
# Meta 内核特性 https://wiki.metacubex.one/config/general
# 统一延迟
# 更换延迟计算方式,去除握手等额外延迟
# 改
#unified-delay: true
unified-delay: true
# TCP 并发
# 同时对所有ip进行连接，返回延迟最低的地址
tcp-concurrent: true
# 外部控制端口
external-controller: :9090
#external-controller: 127.0.0.1:9090
#external-ui: ui
#external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

geodata-mode: true

# Geo 数据库下载地址
# 使用 FastGit 代理 (https://fgit.cf)
# 源地址 https://github.com/MetaCubeX/meta-rules-dat
# 可以更换镜像站但不要更换其他数据库，可能导致无法启动
geox-url:
  #geoip: "https://hub.gitmirror.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  #geosite: "https://hub.gitmirror.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  #mmdb: "https://hub.gitmirror.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"
  geoip: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"
  asn: "https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"

geo-auto-update: true # 是否自动更新 geodata
geo-update-interval: 168 # 更新间隔，单位：小时

# 进程匹配模式
# 路由器上请设置为 off
# always 开启，强制匹配所有进程
# strict 默认，由 Clash 判断是否开启
# off 不匹配进程，推荐在路由器上使用此模式
find-process-mode: strict

# 缓解移动设备耗电问题
# https://github.com/vernesong/OpenClash/issues/2614
disable-keep-alive: true
keep-alive-interval: 1800

# 全局客户端指纹
#改
#global-client-fingerprint: random # 随机指纹
global-client-fingerprint: chrome

# 缓存
profile:
  store-selected: true
  store-fake-ip: true

# 自动同步时间以防止时间不准导致无法正常联网
#ntp:
  #enable: false
  # 是否同步至系统时间，需要 root/管理员权限
  #write-to-system: false
  #server: time.apple.com
  #port: 123
  #interval: 43200

# 域名嗅探
sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

# tun 模式
tun:
  enable: true # enable 'true'
  #stack: system  # or 'gvisor'
  stack: system
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

dns:
  enable: true
  use-hosts: true
  respect-rules: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/15
  fake-ip-filter: ['*', +.lan, +.local]
  default-nameserver: [223.5.5.5, 1.12.12.12, 119.29.29.29, 114.114.114.114]
  proxy-server-nameserver: ['https://223.6.6.6/dns-query', 'https://1.12.12.12/dns-query']
  nameserver: ['https://dns.cloudflare.com/dns-query', 'https://dns.google/dns-query']
  nameserver-policy: { 'geosite:cn,private': ['https://223.6.6.6/dns-query', 'https://1.12.12.12/dns-query'] }
# dns 设置
# 已配置 ipv6
#dns:
  #enable: true
  #listen: :1053
  #ipv6: true
  #respect-rules: true
  ## 路由器个人建议使用 redir-host 以最佳兼容性
  ## 其他设备可以使用 fake-ip
  #enhanced-mode: fake-ip
  #fake-ip-range: 28.0.0.1/8
  #fake-ip-filter:
    #- '*'
    #- '+.lan'
    #- '+.local'
  #default-nameserver:
    #- 223.5.5.5
    #- 119.29.29.29
    #- 114.114.114.114
    #- '[2402:4e00::]'
    #- '[2400:3200::1]'
  #nameserver:
    #- 'tls://8.8.4.4#dns'
    #- 'tls://1.0.0.1#dns'
    ##- 'tls://[2001:4860:4860::8844]#dns'
    #- 'tls://[2606:4700:4700::1001]#dns'
  #proxy-server-nameserver:
    #- https://doh.pub/dns-query
  #nameserver-policy:
    #"geosite:cn,private":
      #- https://doh.pub/dns-query
      #- https://dns.alidns.com/dns-query

# 多入站端口设置
# listeners:
#   - name: hk
#     type: mixed
#     port: 12991
#     proxy: 香港

#   - name: tw
#     type: mixed
#     port: 12992
#     proxy: 台湾

#   - name: sg
#     type: mixed
#     port: 12993
#     proxy: 新加坡

proxies:
  # - name: "WARP"
  #   type: wireguard
  #   server: engage.cloudflareclient.com
  #   port: 2408
  #   ip: "172.16.0.2/32"
  #   ipv6: "2606::1/128"        # 自行替换
  #   private-key: "private-key" # 自行替换
  #   public-key: "public-key"   # 自行替换
  #   udp: true
  #   reserved: "abba"           # 自行替换
  #   mtu: 1280
  #   dialer-proxy: "WARP前置"
  #   remote-dns-resolve: true
  #   dns:
  #     - https://dns.cloudflare.com/dns-query

proxy-groups:
  # 使用 WARP 的用户需要手动在下方的 proxies 字段内添加 WARP
  # 例如 [WARP, 全部节点, 自动选择, 香港, 台湾, 日本, 新加坡, 美国, 其它地区, DIRECT],
  - {
      name: 节点选择,
      type: select,
      proxies:
        [全部节点, 自动选择, 香港, 台湾, 日本, 新加坡, 美国, 其它地区, Mytvsuper, MytvsuperUS, MytvsuperHK, DIRECT],
      icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Quantumult_X.png,
    }
  - { name: 全部节点, <<: *use_p, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Global.png }
  - { name: Mytvsuper, type: select, use: [mytvsuper], icon: https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/rocket(1).png }
  #Emby及倍率
  - { name: Emby, type: select, <<: *use_p, filter: "0.01", proxies: [DIRECT, 倍率, 节点选择], icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Emby.png }
  - { name: EmbyND, type: select, <<: *use_p, filter: "0.01", proxies: [DIRECT, 倍率, 节点选择], icon: https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/niceduck.png }
  - { name: Emby其他, type: select, <<: *use_p, proxies: [DIRECT, 倍率, 节点选择], icon: https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/emby(1).png }
  - { name: 倍率, type: select, proxies: [Mytvsuper, MytvsuperUS, MytvsuperHK], <<: *use_p, filter: "0.01", icon: https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/quanqiu(3).png }
  - { name: TVB, type: select, <<: *use_p, filter: "0.01", proxies: [DIRECT, 倍率, 节点选择], icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/TVB.png }
  # 这里的 dns 指海外解析 dns 走的节点，一般跟随节点选择即可
  #- { name: dns, <<: *pr }
  # WARP 配置链式出站
  # - { name: WARP前置, <<: *pr, exclude-type: "wireguard" }

  - { name: 广告拦截, type: select, proxies: [REJECT, DIRECT, 节点选择], icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Advertising.png }
  - { name: OpenAI, <<: *pr, icon: https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/ChatGPT.png }
  - { name: 微软服务, <<: *pr, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Microsoft.png }
  # Apple 推荐走全局直连
  #- { name: Apple, <<: *pr, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Apple.png }
  - { name: Google, <<: *pr, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Google_Search.png }
  - { name: Telegram, <<: *pr, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Telegram.png }
  #- { name: Twitter, <<: *pr, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Twitter.png }
  #- { name: Pixiv, <<: *pr }
  #- { name: ehentai, <<: *pr }
  # 下面两个看需求启用，打开之后会代理全站流量，可能导致部分版权视频反而无法播放或视频播放速度缓慢
  # 下面 rules 两条也要启用
# - {name: 哔哩哔哩, <<: *pr}
# - {name: 哔哩东南亚, <<: *pr}
  #- { name: 巴哈姆特, <<: *pr }
  - { name: Tiktok, <<: *pr, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/TikTok.png }
  - { name: YouTube, <<: *pr, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png }
  - { name: NETFLIX, <<: *pr, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Netflix.png }
  - { name: Spotify, <<: *pr, icon: https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/spotify(green).png }
  - { name: Github, <<: *pr, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/GitHub_Letter.png }
  #- { name: Steam, <<: *pr }
  #- { name: OneDrive, <<: *pr, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/OneDrive.png }
  
  - {
      name: 国内,
      type: select,
      proxies:
        [
          DIRECT,
          节点选择,
          香港,
          台湾,
          日本,
          新加坡,
          美国,
          其它地区,
          全部节点,
          自动选择,
        ],
      icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/China.png,
    }
  # 其他就是所有规则没匹配到的
  # 可以理解为 ACL4SSR 配置里的 漏网之鱼
  # 换言之，其他走代理就是绕过中国大陆地址，不走就是 GFWList 模式
  - { name: 其他, <<: *pr, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Africa_Map.png }

  # 分隔,下面是地区分组
  - { name: 香港, <<: *use_p, filter: "(?i)港|hk|hongkong|hong kong", icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Hong_Kong.png }
  - { name: 台湾, <<: *use_p, filter: "(?i)台|tw|taiwan", icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Taiwan.png }
  - { name: 日本, <<: *use_p, filter: "(?i)日本|jp|japan", icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Japan.png }
  - { name: 美国, <<: *use_p, filter: "(?i)美|us|unitedstates|united states", icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/United_States.png }
  - { name: 新加坡, <<: *use_p, filter: "(?i)(新|sg|singapore)", icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Singapore.png }
  - {
      name: 其它地区,
      <<: *use_p,
      filter: "(?i)^(?!.*(?:🇭🇰|🇯🇵|🇺🇸|🇸🇬|🇨🇳|港|hk|hongkong|台|tw|taiwan|日|jp|japan|新|sg|singapore|美|us|unitedstates)).*",
      icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/LA_Map.png,
    }
  #- { name: MytvsuperAuto, type: url-test, use: [mytvsuper], filter: "(?i)美|us|unitedstates|united states", icon: https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/rocket(1).png }
  - { name: MytvsuperUS, <<: *LoadBalance, use: [mytvsuper], filter: "(?i)美|us|unitedstates|united states", icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/United_States.png }
  - { name: MytvsuperHK, <<: *LoadBalance, use: [mytvsuper], filter: "(?i)港|HK|HongKong|Hong Kong|国内|CN|CF", icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Hong_Kong.png }
  #- { name: 全部节点, type: select, <<: *use }
  - { name: 自动选择, <<: *use_p, tolerance: 2, type: url-test, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Auto.png }

rules:
  - RULE-SET,Zhilian,国内
  # 若需禁用 QUIC 请取消注释 QUIC 两条规则
  # 防止 YouTube 等使用 QUIC 导致速度不佳, 禁用 443 端口 UDP 流量（不包括国内）

# - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOSITE,cn))),REJECT # quic
  - AND,((RULE-SET,anti-AD),(NOT,((RULE-SET,anti-AD-white)))),广告拦截 # 感谢 Telegram @nextyahooquery 提供的建议
# - GEOSITE,biliintl,哔哩东南亚
# - GEOSITE,bilibili,哔哩哔哩
  - RULE-SET,BlackMatrix7_Direct,DIRECT
  - RULE-SET,Blackmatrix7,广告拦截
  - RULE-SET,AWAvenue,广告拦截
  - RULE-SET,MetaCubeX-AD,广告拦截
  - RULE-SET,DustinWin,广告拦截
  - RULE-SET,EmbyGYF,Emby
  - RULE-SET,Embynd,EmbyND
  - RULE-SET,EmbyQTF,Emby其他
  - RULE-SET,TVBTV,TVB
  - RULE-SET,BeilvMedia,倍率
  - RULE-SET,JPPN,日本
  
  - RULE-SET,TiktokG,Tiktok
  - RULE-SET,games-cn,国内
  - GEOSITE,openai,OpenAI
  - GEOSITE,apple,DIRECT
  - GEOSITE,apple-cn,DIRECT
  #- GEOSITE,ehentai,ehentai
  - GEOSITE,github,Github
  #- GEOSITE,twitter,Twitter
  - GEOSITE,youtube,YouTube
  - GEOSITE,google,Google
  - GEOSITE,google-cn,Google # Google CN 不走代理会导致香港等地区节点 Play Store 异常
  - GEOSITE,telegram,Telegram
  - GEOSITE,netflix,NETFLIX
  #- GEOSITE,bahamut,巴哈姆特
  - GEOSITE,spotify,Spotify
  #- GEOSITE,pixiv,Pixiv
  - GEOSITE,steam@cn,DIRECT
  #- GEOSITE,steam,Steam
  - GEOSITE,onedrive,DIRECT
  - GEOSITE,microsoft,微软服务
  - GEOSITE,geolocation-!cn,其他
# - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOIP,CN))),REJECT # quic
  - GEOIP,google,Google
  - GEOIP,netflix,NETFLIX
  - GEOIP,telegram,Telegram
  #- GEOIP,twitter,Twitter
  - RULE-SET,Streaming,倍率
  - GEOSITE,CN,国内
  - GEOIP,CN,国内
  - MATCH,其他
